### ISSUE TITLE
Ldnode should provide WebIDs

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#105]

**Comment by nicola** [comment]
See https://github.com/nicola/webid-provider

**Comment by gobengo** [comment]
Maybe the standalone command, but it seems like the library part should stay orthogonal to Authorization?

**Comment by nicola** [comment]
Hey @gobengo yes, I am gonna share my work plans soon, so we can think how to proceed on that!

**Comment by sible777** [comment]
What is the status on this? It's pretty interesting and I'd be willing to lend a hand in some way if possible. Shall I just fork and begin hacking away at some functionality to provide webid?

**Comment by nicola** [comment]
@sible777 that would be great!
Let me give you a background of what is going on.
I started sketching this out: https://github.com/solid/node-solid-idp and this assumes that the library [webid](http://npm.im/webid) has a function called generate that given a domain and a spkac will generate a webid+tls certificate. The rest of the module (solid-idp) does all the book-keeping & preparing your workspace, setting up the acls.

I am not planning for this week to get on implementing `generate` in `webid`, let me know and please join the conversation on https://gitter.im/linkeddata/ldnode

**Comment by nicola** [comment]
Maybe @gobengo is interested in join this too. We are slowly setting up a place for the community to hangout, so stay tuned!

**Comment by sible777** [comment]
@nicola I will take a look through the solid-idp module there.

So, does the webid library need to have a generate method implemented? If so I can spend some time looking into that. I had written some node code over the summer that generated webids for my own work so it's possible that I can reuse some of that code. 

I will join in on the chat and get up to speed on what is happening!

**Comment by nicola** [comment]
@sible777 please if you think we could re-use the code that you wrote open an issue here https://github.com/linkeddata/node-webid/issues/new pointing to your code, it could be useful!

**Comment by sible777** [comment]
@nicola Sure thing, I need to review it first, I haven't touched it since the summer, haha. I will review tomorrow and let you know.

**Comment by nicola** [comment]
Working on https://github.com/linkeddata/ldnode/pull/164
