### ISSUE TITLE
Add multipart/form-data file upload

### ISSUE THREAD

**Issue by deiu** [linkeddata/ldnode#108]
Code can be taken and adapted from gold: https://github.com/linkeddata/gold/blob/master/server.go#L884

This is the last bit that's missing from ldnode, which would make it fully compatible with warp.

**Comment by nicola** [comment]
there was an npm module for for that or in express, I will look at that

**Comment by nicola** [comment]
isn't that already there? I think this is what the module rawBody does

**Comment by nicola** [comment]
fixed in https://github.com/linkeddata/ldnode/commit/1bc86b6191827a3b3200dadcd8169429fcd416fd
