### ISSUE TITLE
Custom error pages, especially 401

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#110]
I need to be able to set up a custom return HTML page for HTTP errors, especially error 401 "Unauthenticated".    In practice this is an important part of the on-boarding process, to lead someone who does not have a webid to grab one.

Apache does this with the ErrorDocument directive a la 
 ErrorDocument 404 /Lame_excuses/not_found.html
 ErrorDocument 401 /Subscription/how_to_subscribe.html

See https://httpd.apache.org/docs/2.2/custom-error.html

**Comment by timbl** [comment]
(Note Apache in fact does replacement of many different variables within the page too.  This is less essential but obviously nice)

**Comment by martinmr** [comment]
I found something relevant: http://www.hacksparrow.com/express-js-custom-error-pages-404-and-500.html

However, I think this method only works with 404 and 500 status and it won't work if a previous handler sends the response before these handlers are reached, which all handlers do now.

One idea is to have the handlers set only the status of the response without sending it (unless the status code is 200 or 201 in which case is safe to immediately send the response body), and instead calling next, which looks at the error code and returns the appropriate error page. I'll look into this to see if it's possible.

**Comment by gobengo** [comment]
@martinmr Another good option instead: of just setting the status code to 400/500, pass an error object to next(). Later, you can have an error middleware that knows about the desired way of returning that error as an HTML page (if the client even wants HTML).

See https://github.com/shutterstock/node-common-errors#httpstatus

**Comment by nicola** [comment]
In node you can intercept errors and handle the error page:

```
var ldnode = require('ldnode');
var ldpServer = ldnode();
ldpServer.use(function(err, req, res, next) {
  if(err.status !== 404) {
    return next();
  }
  res.render('Special 404 page.html')
});
ldnode.listen(3456, function () {
  console.log('Server started')
});
```

**Comment by nicola** [comment]
Perfect, I have done some little thinking,
in order to respect @timbl's original idea of ldnode to be _as easy as possible_ I will add `--page-404` and `--page-500` as a command line params so that you can pass the page without coding

**Comment by martinmr** [comment]
I was thinking instead there could be a special folder inside the ldnode
root where ldnode looks for error pages (named for example 404.html). That
way there's no need to create an option for every error. We could have the
folder be a default or a command line option.

In node you can intercept errors and handle the error page:

var ldnode = require('ldnode');
var ldpServer = ldnode();
ldpServer.use(function(err, req, res, next) {
  if(err.status !== 404) {
    return next();
  }
  res.render('Special 404 page.html')
});
ldnode.listen(3456, function () {
  console.log('Server started')
});

—
Reply to this email directly or view it on GitHub
<https://github.com/linkeddata/ldnode/issues/110#issuecomment-127618885>.

**Comment by nicola** [comment]
Ok, let's reshape that into:
You can specify an error page folder `--error-pages` and we look in that folder if we have a page for that error, by default ldnode will provide some nice error pages and with `--no-error-pages` you will have the simple express ones

**Comment by martinmr** [comment]
That sounds good.

**Comment by deiu** [comment]
Why make it an extra CLI parameter? I really like the idea of a default folder. We could then mention in the README that people can replace the default pages there with their own.

**Comment by nicola** [comment]
I am not sure about fixing a folder, especially because you can use ldnode as a library and another library can use it. In other words, there is no way to really locate the `/errors` folder once this happen since ldnode can be in `node_modules` or `node_modules/somelib/node_modules/ldnode`

**Comment by nicola** [comment]
Well, the default error pages will be in a folder and you can edit those, but then this would be really annoying since you override the ldnode repo default pages

**Comment by deiu** [comment]
What if we make the error pages an npm module?

**Comment by nicola** [comment]
I don't think this solve any issue and I think it is not needed..

The solutions discussed above is the following:
- there is a folder in handlers/ called `errors/` and this will have 404.html 401.html etc, these pages will be the default errors
- there is a param to avoid this error pages, since you may want to have no html `--no-error-pages`
- there is a param to specify a different folder than that one `--error-pages`

I think this is pretty much standard

**Comment by deiu** [comment]
Ok, let's go with that for now.

**Comment by martinmr** [comment]
Submitted PR #114 to address this issue.
