### ISSUE TITLE
WebID should not be fetched from external source

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#116]
Tests are too slow, we should use `nock` to mock HTTP requests and speed up the tests, especially ACL

**Comment by deiu** [comment]
There must be a problem if the tests are too slow. It shouldn't take that long for a localhost request.

**Comment by nicola** [comment]
Nope, they are not localhost requests. Most of the ACL request fetch the WebIDs remotely

**Comment by deiu** [comment]
That's not good. We should have a local test WebID then.

**Comment by nicola** [comment]
In other words, all tests should pass if I am offline

**Comment by deiu** [comment]
We are using local keys, so it's just a matter of serving the WebID from a local URI. The immediate issue I see involves disabling secure checks for server cert (since we're fetching from localhost that uses a self-signed cert).

**Comment by nicola** [comment]
serving webId from local uri `>>>` mocking webid request

**Comment by nicola** [comment]
this was done
