### ISSUE TITLE
Internationalization!

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#121]
Ldnode with multi-language support

**Comment by nicola** [comment]
Not for now

**Comment by akuckartz** [comment]
@nicola But why did you close this issue?

**Comment by nicola** [comment]
Hey @akuckartz I was cleaning issues that were outdated and not in the current and near milestones. I am happy to reopen this

**Comment by csarven** [comment]
Created https://github.com/solid/node-solid-server/issues/735 to tackle one aspect of i18n.
