### ISSUE TITLE
ACL mode "Control" on resource must give RW access to ACL file.

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#132]
The "Control" bit set on an ACL means the ability to control the ACL of the resource.  This mean in  a system which has ACL files to store the ACL, that the user  is given read/write access to th erected .acl file.   .ACL files do not have their own .acl.acl files. They of not have to store any ACLs for themselves.

**Comment by nicola** [comment]
See http://github.com/nicola/solid-acl

**Comment by akuckartz** [comment]
How was this resolved?

**Comment by nicola** [comment]
Opps, it was closed in the latest! https://github.com/linkeddata/ldnode/commit/3d809ec9fa8239a886f8b743163fc5d889f3bbf9
