### ISSUE TITLE
If no .acl file is found then access must be DENIED

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#152]
This is a very basic security rule: default safe.   No ACL, no access.  The message below "No ACL policies present - access allowed" signals a major problem.

    Mon, 02 Nov 2015 12:52:26 GMT ldnode:ACL Checking accessTo<Read> to https://81.157.176.49/robots.txt for WebID: 
    Mon, 02 Nov 2015 12:52:26 GMT ldnode:ACL Looking for policies in /Library/WebServer/Documents/robots.txt.acl
     Mon, 02 Nov 2015 12:52:26 GMT ldnode:ACL Error parsing ACL policy: Can't read file: Error: ENOENT, open '/Library/WebServer/Documents/robots.txt.acl' 
    Mon, 02 Nov 2015 12:52:26 GMT ldnode:ACL No policies found in /Library/WebServer/Documents/robots.txt.acl
    Mon, 02 Nov 2015 12:52:26 GMT ldnode:ACL No ACL policies present - access allowed
    Mon, 02 Nov 2015 12:52:26 GMT ldnode:handlers GET -- /robots.txt 
    Mon, 02 Nov 2015 12:52:26 GMT ldnode:handlers GET/HEAD -- Read error: 404 Can't read file: ENOENT, stat '/Library/WebServer/Documents/robots.txt'

**Comment by nicola** [comment]
This is fixed in the new ACL system (yet to be merged) http://github.com/nicola/solid-acl,
I will send a PR for this soon

**Comment by nicola** [comment]
After discussing it wit @deiu, this issue can't be resolved at the moment since in ACL we don't have a way to specify that something can be seen by "everyone" and by doing this change, there is no way I could serve any of my content publicly - yet
