### ISSUE TITLE
Not able to install on node > 0.12.7

### ISSUE THREAD

**Issue by sebilasse** [linkeddata/ldnode#154]
Due to the dependency issue https://github.com/brianmcd/contextify/issues/188 
we are not able to install this e.g. with node v4.x or v5.x for Linux or El Captain.
Unfortunately downgrading to node 0.12.7 is not an option for me.
Any thoughts?

**Comment by deiu** [comment]
Thanks for raising this issue. We'll test and get back to you as soon as possible!

**Comment by sebilasse** [comment]
@deiu The author of contextify fixed the issue (5 mike ago) and I can confirm that this project installs the sane contextify@0.1.15 ! 
I am closing this issue now and probably you could close https://github.com/linkeddata/ldnode/issues/139 as well ...
