### ISSUE TITLE
Add assumedUser command-line option for http://localhost/ mode

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#157]
There is a significant use case for an unauthenticated http:  localhost mode when the server works as an enhanced version of the local file system.   Like when one is on a plane, or just doing local stuff, or a local verison of remote stuff.   In ths case it would be really useful to be able to run the server with a user webid to assume, so that the User: header will be set for each requests, for webapps to use the ID of the user.    So --assumeUser https://ecample.com/fred maybe.

**Comment by nicola** [comment]
So this would skip the authentication bit and always assume that the user has authenticated himself/herself as the `--assumeUser`/`--forceUser`

**Comment by nicola** [comment]
This should do https://github.com/linkeddata/ldnode/pull/165 (ping @deiu)
