### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by sandhawke** [linkeddata/ldnode#18]
A nine syllable name for this project is pretty painful.  Whenever it comes up in conversation I find myself unable to remember the name, and unsure my listeners would understand/parse/recognize/remember it.

I suggest ldnode or ld-node would be a good name, along the lines of ldphp and ldpy, and not far from gold (which is ldgo re-ordered).

**Comment by akuckartz** [comment]
:+1:

**Comment by elf-pavlik** [comment]
please also consider checking out @bergos javascript work on
* https://github.com/bergos/ldp
* https://github.com/zazukoians/rdf-ext
* https://github.com/zazukoians/trifid-ld
etc.

Also https://www.w3.org/community/rdfjs/ doesn't look very active lately but maybe still worth trying to coordinate work on LD tool written in javascript?

**Comment by bergos** [comment]
@sandhawke
Your project looks very similar to [LDApp] (https://github.com/bergos/ldapp). LDApp is very modular. If you don’t like one part of it you can simple replace it with your own code. Out of the box you get WebID authentication, [UAC](https://github.com/bergos/uac) access control, in memory store (that can be replaced by a SPARQL endpoint in the config). A [SPARQL engine](https://github.com/bergos/rdf-query-engine) for RDF-Ext store is now also available. 

[Here](http://ceur-ws.org/Vol-1268/paper13.pdf) a paper I wrote for the ISWC2014.

@elf-pavlik Thanks for pointing me to this project!

**Comment by akuckartz** [comment]
This project has been renamed to ldnode. Can this issue be resolved?

@elf-pavlik Collaboration with other projects such as those led by @bergos can/should better be discussed in separate issues.

**Comment by timbl** [comment]
Sandro renamed the project, so this is issue can be closed

**Comment by elf-pavlik** [comment]
@bergos I think you can still add [LDApp](https://github.com/bergos/ldapp) to https://github.com/linkeddata/SoLiD#servers as an alternative node.js implementation to the one worked on here.
