### ISSUE TITLE
Implement launching LDNode is Single-User mode

### ISSUE THREAD

**Issue by dmitrizagidulin** [linkeddata/ldnode#201]
(Currently being implemented on branch https://github.com/linkeddata/ldnode/tree/ftu-signup , originally PR #182)

LDNode currently works in a multi-user mode (such as being run by a Data Storage Provider like Databox.me), where multiple users can create accounts, and they each get their own subdomain.

The idea behind this issue is: LDNode also needs to support a Single-User use case. This includes:

* Server owner specifies `--single-user-mode` on the command line, when launching, which does the following:
* Serves up a one-time Install app, where the user can go to generate a new account / WebID / certificates, which will then be written in the config file of the server. (and the Install app is disabled)
* Disables new account creation and deletion API endpoints.
* Support running in a sub-directory (so that a user can run an LDNode Solid instance from `usershomepage.com/solid/` instead of root. (This sounds like it's already implemented).

**Comment by nicola** [comment]
done in https://github.com/linkeddata/ldnode/issues/205
