### ISSUE TITLE
Coding style for module.exports

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#23]
### exports.something >> module.exports.something

Following [this](http://www.hacksparrow.com/node-js-exports-vs-module-exports.html) and many other sources, unless we are exporting a function as the only thing we export (instead of an object).

### Hoisting

Mentioned here! #21 

### Exports declared at the end

In some part of the code (e.g. https://github.com/linkeddata/ldnode/blob/master/acl.js) I have seen that we declare some `exports.something`, and then we use them as `exports.something`. I think that makes the code a bit unreadable.

I think declaring an export in the following way is more of a standard in the js community.
```javascript
function Handler () {..
// and at the end of the file
exports.handler = Handler
```

PS: I was going to make some pull reqs, but I think we should first agree on this!

**Comment by martinmr** [comment]
Sounds good. I'll change it over the weekend.

**Comment by martinmr** [comment]
The latest two commits fix most of this issues (except in acl.js but the whole functionality still needs to be tested so I left it alone for now). I'll close this issue but if you notice any of this problems in another place feel free to reopen this issue.
