### ISSUE TITLE
dependency on coffee-script

### ISSUE THREAD

**Issue by melvincarvalho** [linkeddata/ldnode#24]
timbl: > webid@0.1.0 postinstall /devel/github.com/linkeddata/ldnode/node_modules/webid

    > cake build
    sh: cake: command not found

This was trying to do an install from scratch of ldnode

Would it be possible to add the coffee-script dependency to the install?

**Comment by nicola** [comment]
I think they are added (on master, not on npm).
Can you post the full log?

**Comment by martinmr** [comment]
It works on my end. What happens when you run npm install in the node-webid folder? npm should look for cake in ./node_modules/.bin/

**Comment by martinmr** [comment]
Clossing this issue. It is resolved on the master branch, but still not on npm,

**Comment by nicola** [comment]
perfect
