### ISSUE TITLE
Directory URLs are not being redirected to add a trailing slash

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#272]
Now the next problems …. links from the directory to the files are being parsed wrong because the redirection from foo to foo/ is not being noticed I suspect.

The URLs for the children are missing the penultimate bit of the path:
an image which should be /JPEGS/ST000000/SE000003/MR000002.jpg gets linked to from /JPEGS/ST000000/SE000003 as /JPEGS/ST000000/MR000002.jpg
when I load /JPEGS/ST000000/SE000003 in the browser
If I load the browser with /JPEGS/ST000000/SE000003/ it is fine
Are you sure ldnode is doing the redirect?

**Comment by timbl** [comment]
deiu 
I remember implementing the redirect in gold. I'm not sure Nicola implemented it in ldnode.
@deiu checking

timbl
It is fairly basic — I am surprised if it isnn;t there — other possibility is FFox is hiding it

deiu 
xhr requests don't show redirects btw

timbl 
I now that is a bug. But the final location header if there is one maybe would work
We haven’t had this problem thoygh before … over the years

deiu 
Yes, I don't think it got implemented in ldnode
@deiu fixing now

timbl
strange — any server which handles index.html for example has to do that redirect for the links int the html to work!
it must be a router in express.
Maybe it has been overridden by the ldnode code.

**Comment by mediaprophet** [comment]
Q: How is the image derivatives and metadata being handled?

**Comment by nicola** [comment]
@deiu @timbl  does this https://github.com/linkeddata/ldnode/pull/273 fix?

**Comment by deiu** [comment]
Yes, I believe so.

**Comment by nicola** [comment]
Fixed in https://github.com/linkeddata/ldnode/commit/a44e320947a33e902e538f612bfff47f3bdc3fef
