### ISSUE TITLE
Reinstating original Embedded App functionality

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#274]
In the process of renaming the "skin" functionality to "defaultApp" we have lost what I actually meant as the skin.    I am happy to call it something else than "skin"  -- maybe "fallbackApp" or something

- Instead of redirecting the client to a remote viewer app, which messed up the URI bar, the app is returned directly as a text/html  file.   The file's origin is then the same as the data. 

- The very small HTML file is stored locally just like an error file.  A default version can be kept in the code.
- It is invoked whenever the content negotiation perceives that the client is a browser capable running a web app, but is not capable of handling the data of the requested resource.    It is invoked if the browsers ability to handle HTML times 0.7 (say)   is greater than its q ability to handle the data itself.   Ask me if you do not understand content negotiation. 

How about  --fallback media/html/tabulatorSkin.html  for the command line app?    It would be an alternative to --defaultApp

**Comment by timbl** [comment]
An example skin file is in https://github.com/linkeddata/tabulator/blob/master/js/mashup/skin.html
I'm using it for my webid at the moment
https://www.w3.org/People/Berners-Lee/card#i

**Comment by deiu** [comment]
Implemented in https://github.com/linkeddata/ldnode/commit/1a706d4181fd67bee676d03e8ab9040112ad65e5
