### ISSUE TITLE
please add account name to displayed part of certificate

### ISSUE THREAD

**Issue by sandhawke** [linkeddata/ldnode#277]
Gold writes my certs in a way that I can tell them apart.   ldnode does not.   

Gold's for me look like "Sandro Hawke [on sandro3.example.com]" while ldnode just has name and date.

**Comment by nicola** [comment]
At the moment this is an option (ldnode as a library allows you to change that), but I will make this a default setting

**Comment by sandhawke** [comment]
Thanks

**Comment by nicola** [comment]
This should fix #306
