### ISSUE TITLE
PATCH only inserting the last set of triples

### ISSUE THREAD

**Issue by dmitrizagidulin** [linkeddata/ldnode#281]
Came across this while working on the type registry code. Sent a PATCH to an ldnode resource containing 3 insert statements:

```
INSERT DATA { <https://localhost:8443/settings/publicTypeIndex.ttl#Z1L6Rhd> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/solid/terms#TypeRegistration> . } ;
INSERT DATA { <https://localhost:8443/settings/publicTypeIndex.ttl#Z1L6Rhd> <http://www.w3.org/ns/solid/terms#forClass> <http://www.w3.org/2006/vcard/ns#AddressBook> . } ;
INSERT DATA { <https://localhost:8443/settings/publicTypeIndex.ttl#Z1L6Rhd> <http://www.w3.org/ns/solid/terms#instance> <https://localhost:8443/contacts/myNewAddrBook.ttl> . }
```

But only the last set of triples (the one involving `terms:instance`) got inserted, the rest were dropped.
(Seems to be working correctly in Gold)

**Comment by nicola** [comment]
Is this a patch to a normal existing resource?

**Comment by dmitrizagidulin** [comment]
@nicola - Yes, patch to a normal `.ttl` existing resource.

**Comment by dmitrizagidulin** [comment]
(Fwiw, a patch to a non-existing resource works as well and creates a resource, but does the same thing -- only writes the last set of triples)

**Comment by dmitrizagidulin** [comment]
It looks like our ldnode unit tests only use one statement. We should fix that at some point, though the current test setup compares strings directly instead of parsing the resulting file.

**Comment by dmitrizagidulin** [comment]
Looks like an issue with `$rdf.sparqlUpdateParser()`. Opened upstream issue https://github.com/linkeddata/rdflib.js/issues/117.

**Comment by dmitrizagidulin** [comment]
Sounds like this is the intended behavior, for RDFLib. Upstream bug is closed as 'won't fix', closing this one too. Will be fixed on the client side (only post one set of INSERT statements, with the full graph in that).
