### ISSUE TITLE
Please allow option to use mashlib for folders too

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#289]
As the mashlib has various ways to handle directories/folders/containers, including embedded Warp iframe, it would be nice to have a flag so that they were by default handled with the default bowser, just as data files are.

![screen shot 2016-03-14 ](https://cloud.githubusercontent.com/assets/1254848/13750541/5b09ee7c-e9dc-11e5-8b70-f6b475f4d3a1.png)

**Comment by deiu** [comment]
In fact, we don't need to implement anything. It turns out you can disable certain options by prefixing them with `--no-*`. In your case, you can try passing the following param -- `--no-file-browser`.

**Comment by nicola** [comment]
@timbl did it work for you?

**Comment by nicola** [comment]
works!
