### ISSUE TITLE
Is the Makefile still needed?

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#29]
Since `package.json` contains the script `starts` and the script `test`, is the Makefile still needed?
I am a bit confused of the references to tabulator and /dev/WWW (which I assume they were probably originally used for quick & dirty testing)

**Update**

What I am seeing now is that in order to run the tests one has to run `ldnode` with some specific settings and just by doing `make` you start ldnode ready for test settings. However this should all be done by `npm test`. The user doesn't want to see or do too many things when running the tests

**Comment by martinmr** [comment]
The makefile is used to start the server with different options (e.g. webid support).
The references to /dev/www are there because Tim wrote the tests for sparql-update support and they depend on some python scripts. I agree that they should be cleaned up but they are still separate tests from the ones in test.js.

**Comment by nicola** [comment]
Hey @martinmr, I still think this is something is still to be fixed, since having a Makefile with undocumented functionalities and using files not in the repo may confuse new developers. 

Starting the server & testing should be in `package.json`.

**Comment by nicola** [comment]
I think this should be fixed in https://github.com/linkeddata/ldnode/commit/23d540f88f41952fa689961bf6d8a0132b8c3d8e, where there is no need for the Makefile

**Comment by martinmr** [comment]
I think the node tests don't need the Makefile but I am not sure about Tim's old tests.

**Comment by nicola** [comment]
perfect will ask tomorrow!

**Comment by timbl** [comment]
The Makefile is not needed, so long as the tests from test/Makefile are incorporated into the new test setup.   I don't need those make commands (useful though they are for testing.)

**Comment by martinmr** [comment]
I think we should keep the Makefile but rewrite it to match the current command line options and not use for automated testing. That way we have an easy way to start the server in certain configurations. For example, I could run:
```
make no-ssl
```
to start an http server and so on.

**Comment by sandhawke** [comment]
My sense is the idiom with node.js is to use "npm run" for that kind of thing.

**Comment by nicola** [comment]
+1 for npm run

**Comment by martinmr** [comment]
Closing issue as Makefile is already removed in master.
