### ISSUE TITLE
acl scope question

### ISSUE THREAD

**Issue by satra** [linkeddata/ldnode#297]
when using the apps without authentication, plume or timeline cannot read posts that have open permissions, if the parent folder does not have `everyone -> read` permission. 

so this works:

`curl -D - -L -H "Accept: text/turtle" https://satra.databox.me/Timeline/2016-03-22/47c229'

but these two don't:

```
curl -D - -L -H "Accept: text/turtle" https://satra.databox.me/Timeline/2016-03-22/
curl -D - -L -H "Accept: text/turtle" https://satra.databox.me/Timeline/
```

is this by design? if so is there a way to get at internal public pieces by querying a parent node?

and more generally, can one get at all my everyone read info using:

```
curl -D - -L -H "Accept: text/turtle" https://satra.databox.me/
```

**Comment by sandhawke** [comment]
I think the idea is a non-public container means the public resources inside it are essentially unlisted.   Is that okay?

**Comment by sandhawke** [comment]
BTW, this probably belongs as an issue on solid/solid instead of ldnode, unless you suspect a bug in ldnode.   (Fwiw databox.me currently runs gold not ldnode.)

**Comment by satra** [comment]
@sandhawke - with all the pieces going on  i didn't know where best to post. i'll move it solid and make some suggestions there.

also should i use databox.me or something else? will move to my own server in the future, but for now, i can test all things with this.

**Comment by sandhawke** [comment]
For testing, I would use both databox.me (running gold) and databox2.com (running ldnode) so that you're more likely to catch bugs in software.
