### ISSUE TITLE
New repo for tests

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#30]
The tests that we have in our folder are *acceptance tests*, in other words we are testing if the API works as expected. The same tests can be used for any other LDP implementation, e.g. gold.

So, my idea is that we could just take this tests out in a new package like `ld-test` or `superld` that tests a LDP. So that in this repo we can test more on unit testing.

This is just an idea, otherwise we could just leave things as they are, which are great!

**Comment by deiu** [comment]
+1 to having an LDP test harness.

**Comment by akuckartz** [comment]
:+1:

**Comment by martinmr** [comment]
This seems like a good idea. The only problem I see is that the current tests depend on running the test server in ldnode which needs to be started before running the tests.

**Comment by nicola** [comment]
I agree with martin. We shall leave this for now
