### ISSUE TITLE
ldnode crash on upload from Warp

### ISSUE THREAD

**Issue by dmitrizagidulin** [linkeddata/ldnode#316]
databox2.com went down (@cgutteridge was uploading files through Warp, I think) a few mins ago. Here's the stack trace from the error console:

```
 ldnode:idp Account on cgutteridge.databox2.com is not available / +6s
ldnode:authentication User: https://cgutteridge.databox2.com/profile/card#me +1ms
ldnode:ACL Can https://cgutteridge.databox2.com/profile/card#me Read https://cgutteridge.databox2.com/? +0ms
ldnode:ACL Check if acl exist: https://cgutteridge.databox2.com/.acl +0ms
ldnode:ACL Found policies in https://cgutteridge.databox2.com/.acl +16ms
ldnode:ACL Checking for accessType:accessTo +0ms
ldnode:ACL Read access allowed (as agent) for: https://cgutteridge.databox2.com/profile/card#me +1ms
ldnode:ACL ACL policy found +1ms
ldnode:index Looking for index in /index.html +1ms
ldnode:get / on cgutteridge.databox2.com +6ms
ldnode:handlers GET -- Reading directory +2ms
ldnode:handlers Files in directory: .acl,cjgtest,cjgtest.acl,dev8d_programme.rdf,inbox,pastebin,profile,prog.ttl,settings,soton-opd.ttl +0ms
/usr/lib/node_modules/ldnode/lib/http-error.js:19
    this.status = err.status || err.code === 'ENOENT' ? 404 : 500
                     ^

TypeError: Cannot read property 'status' of null
    at new HTTPError (/usr/lib/node_modules/ldnode/lib/http-error.js:19:22)
    at HTTPError (/usr/lib/node_modules/ldnode/lib/http-error.js:5:12)
    at /usr/lib/node_modules/ldnode/lib/ldp.js:163:29
    at /usr/lib/node_modules/ldnode/lib/ldp.js:93:14
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

**Comment by cgutteridge** [comment]
Yup. I uploaded a .rdf (XML) file then reuploaded it as .ttl should that be relevant.

**Comment by nicola** [comment]
I am not sure what part of code is not returning the error status,
but I fixed the bug that makes it crash here: https://github.com/linkeddata/ldnode/pull/317

**Comment by nicola** [comment]
did this fix your issue @cgutteridge ?

**Comment by cgutteridge** [comment]
nope! https://cgutteridge.databox2.com/ gives


Secure Connection Failed

The connection to the server was reset while the page was loading.

     The page you are trying to view cannot be shown because the 
authenticity of the received data could not be verified.
     Please contact the web site owners to inform them of this problem.

Learn more…

Report errors like this to help Mozilla identify and block malicious sites



On 15/04/2016 14:34, Nicola Greco wrote:
>
> did this fix your issue @cgutteridge <https://github.com/cgutteridge> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/linkeddata/ldnode/issues/316#issuecomment-210582341>Web 
> Bug from 
> https://github.com/notifications/beacon/AAfK64WEq4ArtFQGVYOjkcadOoBETgc6ks5p39pOgaJpZM4IHrpZ.gif
>

-- 
Christopher Gutteridge -- http://users.ecs.soton.ac.uk/cjg

University of Southampton Open Data Service: http://data.southampton.ac.uk/
You should read the ECS Web Team blog: http://blogs.ecs.soton.ac.uk/webteam/

**Comment by nicola** [comment]
Fixed in person
