### ISSUE TITLE
How to run secure-tests.js?

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#35]
At the moment I am trying to run the tests but they all fail since they can't find the resources, hence the socket hang-up.

(I know they are under development! This is just to know how they work!)

**Comment by martinmr** [comment]
On the projects root  folder execute

```make run-for-test-login

and in another terminal

```./node_modules/.bin/mocha test/secure-test.js

**Comment by deiu** [comment]
This info should be in a README somewhere.

**Comment by nicola** [comment]
I am working on https://github.com/nicola/ldnode/tree/routers which is a rewrite of `server.js` so that an ldp can be just loaded as a router, can be started programmatically or can be a command line. In this way, there will be no need of the make file to start a test and one can encode the parameters for the testing straight into the .js test files.

So, although documentation is preferred, in this case, it will be soon deprecated.

I wanted to know how to run the tests to make sure my new changes are passing the previous tests

**Comment by nicola** [comment]
Fixed in https://github.com/linkeddata/ldnode/commit/23d540f88f41952fa689961bf6d8a0132b8c3d8e
