### ISSUE TITLE
Options.js should not have static attributes

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#36]
Assuming we want to start two ldnode running, editing the options' attribute will statically edit the options of each ldnode instance.

This problem does not arise in the current version of ldnode that has to be run from terminal, but it does in my fork where I am transforming ldnode into a library rather than a command line tool.

See my branch nicola/ldnode#routes for reference

**Comment by martinmr** [comment]
Would having the options be declared as

```
var options = {};
options.fileBase = "";
```
instead of 
```
exports.fileBase = "";
```
and having modules dependent on options.js call a method such as
```
options.set('fileBase', "newValue")
```
fix the issue?

**Comment by nicola** [comment]
I guess it won't.We need to have var options = parseOutput(Argv)

- Typed on a phone by Nicola himself




On Wed, Jul 8, 2015 at 4:14 PM -0700, "Martin Martinez Rivera" <notifications@github.com> wrote:












Would having the options be declared as

var options = {};
options.fileBase = "";




instead of 

exports.fileBase = "";




and having modules dependent on options.js call a method such as

options.set('fileBase', "newValue")




fix the issue?

**Comment by martinmr** [comment]
Another question: if ldnode is being run as a library, where would the argv argument come from?

**Comment by nicola** [comment]
See my repo, or come to IRC for a chat.

- Typed on a phone by Nicola himself




On Wed, Jul 8, 2015 at 4:21 PM -0700, "Martin Martinez Rivera" <notifications@github.com> wrote:












Another question: if ldnode is being run as a library, where would the argv argument come from?

**Comment by nicola** [comment]
Sorry for double commenting, I just updated the readme that shows how to use it: https://github.com/nicola/ldnode/tree/routers

**Comment by nicola** [comment]
I will do this

**Comment by nicola** [comment]
This problem resulted to be drastically more important than it originally appeared, since this forces the entire library to be only used as one instance only.

This is requiring a big re-writing that I hope to finish by tomorrow.

**Comment by martinmr** [comment]
That's fine. I had not started working on it.

**Comment by nicola** [comment]
I fixed this in my fork. There are two tests not running, do you think you can have a look?

https://travis-ci.org/linkeddata/ldnode/builds/70241967 <https://travis-ci.org/linkeddata/ldnode/builds/70241967>

**Comment by martinmr** [comment]
They were running yesterday on the master branch. I'll have a look.

On Thu, Jul 9, 2015 at 1:31 PM, Nicola Greco <notifications@github.com>
wrote:

> I fixed this in my fork. There are two tests not running, do you think you
> can have a look?
>
> https://travis-ci.org/linkeddata/ldnode/builds/70241967 <
> https://travis-ci.org/linkeddata/ldnode/builds/70241967>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkeddata/ldnode/issues/36#issuecomment-120080454>.
>



-- 
Martin Martinez Rivera
Massachusetts Institute of Technology
Courses 6-3
Class of 2014

**Comment by nicola** [comment]
are you free on IRC in about 30 mins?

**Comment by martinmr** [comment]
No. I am about to go out eat/ run some errand. I should be back at about
3:30-4:00 PM EST. Does that time still work for you?

On Thu, Jul 9, 2015 at 1:40 PM, Nicola Greco <notifications@github.com>
wrote:

> are you free on IRC in about 30 mins?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkeddata/ldnode/issues/36#issuecomment-120083000>.
>



-- 
Martin Martinez Rivera
Massachusetts Institute of Technology
Courses 6-3
Class of 2014

**Comment by nicola** [comment]
Perfect, let’s try!

**Comment by nicola** [comment]
I am on IRC, gitter is down for me.

**Comment by martinmr** [comment]
I solved the bug. You were using the wrong ACL handler for PUT, PUSH, and PATCH requests. Commit https://github.com/linkeddata/ldnode/commit/bc005b2423a3fdb383b1dc1f07e9e4b338774e49 fixes the issue. You can pull to your repository.

**Comment by nicola** [comment]
Fixed in https://github.com/linkeddata/ldnode/commit/23d540f88f41952fa689961bf6d8a0132b8c3d8e
