### ISSUE TITLE
User: header is not sent

### ISSUE THREAD

**Issue by timbl** [linkeddata/ldnode#64]
The Solid world requires  the User: header to be sent back when a user is logged on with webid/TLS

Typical response headers from a GET authenitcated by webid currently:
	
status	 200
status Text	OK
connection	keep-alive
content length	1367428
content type	text/n3; charset=utf-8
etag	W/"14dd84-P7TE3CNZwvMq1mvb6/zJ+w"
link	<http://www.w3.org/ns/ldp#Resource>; rel='type', </TimBL/Automation/mother/state.n3.changes>; rel='changes'
ms author via	 SPARQL
updates via	 /TimBL/Automation/mother/state.n3.changes
x powered by	Express
x response time	 4.160ms

**Comment by martinmr** [comment]
I said I was going to work on that earlier but I haven't got around to it. I'll work on it today. It should be a very simple change.

**Comment by timbl** [comment]
Yes - you have the URI from ACLs and you can seee where the other  headers are added

**Comment by martinmr** [comment]
Here's the pull request: https://github.com/linkeddata/ldnode/pull/67
The tests pass on my machine but I am going to wait for travis to complete the tests before merging.

**Comment by martinmr** [comment]
Fix and merged into master.
