### ISSUE TITLE
Code review: understanding the reason of `parse.js`

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#81]
Most of the function in `parse.js` implement what `$rdf.parse` is for, correct?

If not, this is a very valuable too and it should be separated in a different lib `linkeddata-parse` / `ldnode-parse`

**Comment by martinmr** [comment]
I originally wrote the parse code in parse.js and then I adopted into rdflib. The main difference is that the code in rdflib adds the input to a graph and the code in parse.js directly converts json/nquads to n3 without the middle step. If we changed the code to use rdflib a lot of time would be wasted parsing the input into a graph only to immediately serialize it. 

I don't think the code warrants to be in its own package. It's merely an optimization that's not general enough to be useful to other people in the way $rdflib.parse is.

**Comment by nicola** [comment]
I still think that cleaning that code can be useful to everybody trying to tackle the same problem (avoiding passing through rdflib). Let's leave it for now, but it is something we should consider
