### ISSUE TITLE
suffixMeta should be defined from opts/commandline

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#89]
Same as any other suffix, `suffixAcl`, etc..

**Comment by martinmr** [comment]
I can work on this if no one else has already started working on it.

**Comment by nicola** [comment]
I had a draft, but I think I have to start that again!

I remembered this was either not trivial or it had to carry `options` all over those functions.
The idea is to not create global variable that would make `ldnode` single instance only.

Let me know (the proxy issue is needed if you want!)

**Comment by martinmr** [comment]
Ok. I'll let you do it because you are more familiar with how the options work after the refactoring.

**Comment by nicola** [comment]
Perfect!



On Fri, Jul 17, 2015 at 9:01 PM -0700, "Martin Martinez Rivera" <notifications@github.com> wrote:












Ok. I'll let you do it because you are more familiar with how the options work after the refactoring.

**Comment by nicola** [comment]
doing in #97
