### ISSUE TITLE
Missing CORS support.

### ISSUE THREAD

**Issue by deiu** [linkeddata/ldnode#91]
ldnode does not currently support CORS headers. We need to have at least `Access-Control-Allow-Origin` support.

**Comment by akuckartz** [comment]
:+1:

**Comment by nicola** [comment]
Work started here https://github.com/linkeddata/ldnode/pull/92

**Comment by nicola** [comment]
done in https://github.com/linkeddata/ldnode/commit/9f929ba15b817ceb8c9ef0cf80062d4248a3b738
