### ISSUE TITLE
Not working on warp

### ISSUE THREAD

**Issue by nicola** [linkeddata/ldnode#95]
Gold (or databox.me) returns a listing of this kind:

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .

<>
    a <http://www.w3.org/ns/ldp#BasicContainer>, <http://www.w3.org/ns/ldp#Container>, <http://www.w3.org/ns/posix/stat#Directory> ;
    <http://www.w3.org/ns/ldp#contains> <Applications/>, <Family/>, <Friends/>, <Preferences/>, <Private/>, <Public/>, <Work/>, <profile/> ;
    <http://www.w3.org/ns/posix/stat#mtime> "1435333390" ;
    <http://www.w3.org/ns/posix/stat#size> "4096" .

<Applications/>
    a <http://www.w3.org/ns/ldp#BasicContainer>, <http://www.w3.org/ns/ldp#Container>, <http://www.w3.org/ns/posix/stat#Directory> ;
    <http://www.w3.org/ns/posix/stat#mtime> "1435333433" ;
    <http://www.w3.org/ns/posix/stat#size> "4096" .
```

However ldnode returns this:

```
@prefix n0: </>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix st: <http://www.w3.org/ns/posix/stat#>.
@prefix keys: </keys/>.
@prefix res: </resources/>.

<#>
    ldp:contains
        </acl.js>,
        </formats.js>,
        </http.js>,
        n0:keys,
        </params.js>,
        </patch.js>,
        n0:resources;
    st:mtime
       1437300761000;
    st:size
       306.
   </acl.js> st:mtime 1437139220000; st:size 42866 .
   </formats.js> st:mtime 1437090751000; st:size 1982 .
   </http.js> st:mtime 1437302617000; st:size 6750 .
   keys: st:mtime 1436972622000; st:size 340 .
   </params.js> st:mtime 1437089197000; st:size 3349 .
   </patch.js> st:mtime 1437090751000; st:size 5410 .
   res: st:mtime 1437302621000; st:size 986 .
```

Since warp looks for `POSIX(Directory)` in here https://github.com/linkeddata/warp/blob/gh-pages/src/app/list/list.js#L188

- Either we need to specify that attribute in ldnode
- We have to change how warp does that

**Comment by deiu** [comment]
I can patch WARP to look for ldp:BasicContainer instead of posix:Directory, but it looks like ldnode does not add any types for the resources. Martin and I talked about adding the POSIX types, but he must have forgotten.

**Comment by martinmr** [comment]
ldnode will add type for resources only if they are a turtle file or have a .meta file . Otherwise it doesn't. I thought this was the desired behavior.

**Comment by deiu** [comment]
Yes, that is the intended behavior. However, every reason must have a default type already:
 * container -> posix:Directory and ldp:BasicContainer
 * file -> posix:File

**Comment by martinmr** [comment]
This should be a simple change but I'll wait for nicola's refactoring before submitting a PR

**Comment by nicola** [comment]
Martin, I am out the Internet for most of the week,

Meanwhile, you can either work in the current branch, I will handle the conflict or, if you have gone through  my code already, you can PR it!



On Mon, Jul 20, 2015 at 5:31 PM -0700, "Martin Martinez Rivera" <notifications@github.com> wrote:












This should be a simple change but I'll wait for nicola's refactoring before submitting a PR

**Comment by nicola** [comment]
Fixed in https://github.com/linkeddata/ldnode/pull/97
